name: Release

on:
  workflow_dispatch:

jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest

    permissions:
      id-token: write # mandatory for trusted publishing
      contents: write # required for `rake release` to push the release tag

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler: latest
          bundler-cache: true

      - uses: rubygems/release-gem@v1
